### ISSUE TITLE
Send with HTTP instead of ZMQ

### ISSUE THREAD

**Issue by SebastianNeiswanger** [CreativeSolutionsGroup/smart-events-rust-terminal#41]
We need to move functions away from utilizing ZMQ to using HTTP.

- [x] Add a `BOOPER_ID` to the env for the units to use instead of a mac_address.
- [x] Heartbeat. `POST` request with a JSON body containing all check-ins in the system. If we receive a `201` then proceed to purge all of the **sent** check-ins from the local database.
- [x] check-ins. `PUT` request with a query string of `id=${BOOPER_ID}` (not exact implementation, just the idea). You don't need to worry about a response. Just send this out once every 3 seconds.

**Comment by ashlyndevries** [comment]
@awtpi314
