### ISSUE TITLE
Create cache sending

### ISSUE THREAD

**Issue by SebastianNeiswanger** [CreativeSolutionsGroup/smart-events-rust-terminal#8]
This story is similar to [these functions](https://github.com/CreativeSolutionsGroup/smart-events-terminal-app/blob/659f0efb5d7da57ca694327fcebe3b45ad564ce8/src/main.ts#L100-L143). It will also implement ZMQ.

**Comment by SpBills** [comment]
@SebastianNeiswanger how we doin
